[package]
name = "rusty-pico"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
embedded-hal = "1.0.0"
heapless = "0.8.0"
numtoa = "0.2.4"
panic-halt = "0.2.0"
rp-pico = "0.9.0"
usb-device = "0.3.2"
usbd-serial = "0.2.2"
